### YamlMime:UniversalReference
ms.openlocfilehash: 388e022c41872f41fc3ff1a4f5bee98d77b1c567
ms.sourcegitcommit: 8f2555cd23e454ff79e27bd3ed0a6f65b08c1c9e
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/10/2018
ms.locfileid: "48523545"
items:
- uid: '@azure/event-hubs.ErrorNameConditionMapper'
  name: ErrorNameConditionMapper
  fullName: ErrorNameConditionMapper
  children:
  - '@azure/event-hubs.ErrorNameConditionMapper.ArgumentError'
  - '@azure/event-hubs.ErrorNameConditionMapper.UnauthorizedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ConnectionForcedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ConnectionRedirectError'
  - '@azure/event-hubs.ErrorNameConditionMapper.DecodeError'
  - '@azure/event-hubs.ErrorNameConditionMapper.DetachForcedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ErrantLinkError'
  - '@azure/event-hubs.ErrorNameConditionMapper.FrameSizeTooSmallError'
  - '@azure/event-hubs.ErrorNameConditionMapper.FramingError'
  - '@azure/event-hubs.ErrorNameConditionMapper.HanldeInUseError'
  - '@azure/event-hubs.ErrorNameConditionMapper.IllegalStateError'
  - '@azure/event-hubs.ErrorNameConditionMapper.InternalServerError'
  - '@azure/event-hubs.ErrorNameConditionMapper.InvalidFieldError'
  - '@azure/event-hubs.ErrorNameConditionMapper.InvalidOperationError'
  - '@azure/event-hubs.ErrorNameConditionMapper.LinkRedirectError'
  - '@azure/event-hubs.ErrorNameConditionMapper.MessageLockLostError'
  - '@azure/event-hubs.ErrorNameConditionMapper.MessageTooLargeError'
  - '@azure/event-hubs.ErrorNameConditionMapper.MessagingEntityDisabledError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ArgumentOutOfRangeError'
  - '@azure/event-hubs.ErrorNameConditionMapper.OperationCancelledError'
  - '@azure/event-hubs.ErrorNameConditionMapper.PreconditionFailedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.QuotaExceededError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ReceiverDisconnectedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ResourceDeletedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ResourceLockedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SenderBusyError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ServerBusyError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ServiceCommunicationError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ServiceUnavailableError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SessionCannotBeLockedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SessionLockLostError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SessionWindowViolationError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SystemError'
  - '@azure/event-hubs.ErrorNameConditionMapper.TransferLimitExceededError'
  - '@azure/event-hubs.ErrorNameConditionMapper.UnattachedHandleError'
  - '@azure/event-hubs.ErrorNameConditionMapper.NotImplementedError'
  langs:
  - typeScript
  type: enum
  summary: <span data-ttu-id="67d33-101">错误名称映射到 amqp 错误条件。</span><span class="sxs-lookup"><span data-stu-id="67d33-101">Maps the Error names to the amqp error conditions.</span></span>
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ArgumentError'
  name: ArgumentError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-102">当收到不正确的参数时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-102">Error is thrown when an incorrect argument was received.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.UnauthorizedError'
  name: UnauthorizedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-103">连接参数为错误和服务器拒绝了连接时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-103">Error is thrown when the connection parameters are wrong and the server refused the connection.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ConnectionForcedError'
  name: ConnectionForcedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-104">操作员 intervened 出于某种原因关闭连接时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-104">Error is thrown when an operator intervened to close the connection for some reason.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ConnectionRedirectError'
  name: ConnectionRedirectError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-105">当容器不再为当前连接上可用，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-105">Error is thrown when the container is no longer available on the current connection.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.DecodeError'
  name: DecodeError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-106">当无法解码数据时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-106">Error is thrown when data could not be decoded.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.DetachForcedError'
  name: DetachForcedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-107">操作员 intervened 出于某种原因分离时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-107">Error is thrown when an operator intervened to detach for some reason.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ErrantLinkError'
  name: ErrantLinkError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-108">输入接收错误分离的链接时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-108">Error is thrown when input was received for a link that was detached with an error.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.FrameSizeTooSmallError'
  name: FrameSizeTooSmallError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-109">当对等方无法发送一个帧，因为将太大，无法商定的最大帧大小的范围内的行为原语使用当前有效的值的最小编码时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-109">Error is thrown when the peer cannot send a frame because the smallest encoding of the performative with the currently valid values would be too large to fit within a frame of the agreed maximum frame size.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.FramingError'
  name: FramingError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-110">不能从传入的字节流形成有效框架标头时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-110">Error is thrown when a valid frame header cannot be formed from the incoming byte stream.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.HanldeInUseError'
  name: HanldeInUseError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-111">当附加收到使用句柄已使用的附加链接时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-111">Error is thrown when an attach was received using a handle that is already in use for an attached link.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.IllegalStateError'
  name: IllegalStateError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-112">对等方发送中的当前状态不允许的帧时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-112">Error is thrown when the peer sent a frame that is not permitted in the current state.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.InternalServerError'
  name: InternalServerError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-113">当发生了内部服务器错误时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-113">Error is thrown when an internal server error occured.</span></span> <span data-ttu-id="67d33-114">你可能已发现一个 bug？</span><span class="sxs-lookup"><span data-stu-id="67d33-114">You may have found a bug?</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.InvalidFieldError'
  name: InvalidFieldError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-115">在帧正文中传递无效的字段和操作无法继续时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-115">Error is thrown when an invalid field was passed in a frame body, and the operation could not proceed.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.InvalidOperationError'
  name: InvalidOperationError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-116">当尝试操作，但不是允许时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-116">Error is thrown when an operation is attempted but is not allowed.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.LinkRedirectError'
  name: LinkRedirectError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-117">提供的地址不能被解析为在当前容器终点时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-117">Error is thrown when the address provided cannot be resolved to a terminus at the current container.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.MessageLockLostError'
  name: MessageLockLostError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-118">对消息锁丢失时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-118">Error is thrown when the lock on the message is lost.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.MessageTooLargeError'
  name: MessageTooLargeError
  children: []
  langs:
  - typeScript
  summary: '<span data-ttu-id="67d33-119">发送的消息太大，将发生错误： 最大大小为 256 Kb。</span><span class="sxs-lookup"><span data-stu-id="67d33-119">Error is thrown when the message sent is too large: the maximum size is 256Kb.</span></span>'
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.MessagingEntityDisabledError'
  name: MessagingEntityDisabledError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-120">尝试访问/连接到已禁用的消息传送实体时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-120">Error is thrown when trying to access/connect to a disabled messaging entity.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ArgumentOutOfRangeError'
  name: ArgumentOutOfRangeError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-121">当自变量的值的不在允许范围内时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-121">Error is thrown when an argument has a value that is out of the admissible range.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.OperationCancelledError'
  name: OperationCancelledError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-122">当服务器将取消该操作由于内部问题时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-122">Error is thrown when server cancels the operation due to an internal issue.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.PreconditionFailedError'
  name: PreconditionFailedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-123">不应满足才能执行操作的条件时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-123">Error is thrown when a condition that should have been met in order to execute an operation was not.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.QuotaExceededError'
  name: QuotaExceededError
  children: []
  langs:
  - typeScript
  summary: >-
    <span data-ttu-id="67d33-124">引发错误超过了 Azure 事件中心服务总线配额。</span><span class="sxs-lookup"><span data-stu-id="67d33-124">Error is thrown the the Azure EventHub/ServiceBus quota has been exceeded.</span></span>

    <span data-ttu-id="67d33-125">定期重置配额，此操作将需要在此之前等待。</span><span class="sxs-lookup"><span data-stu-id="67d33-125">Quotas are reset periodically, this operation will have to wait until then.</span></span>

    <span data-ttu-id="67d33-126">消息实体已达到其最大允许大小。</span><span class="sxs-lookup"><span data-stu-id="67d33-126">The messaging entity has reached its maximum allowable size.</span></span>

    <span data-ttu-id="67d33-127">如果已经在每使用者组级别上打开最大接收方数（即 5），则可能发生此情况。</span><span class="sxs-lookup"><span data-stu-id="67d33-127">This can happen if the maximum number of receivers (which is 5) has already been opened on a per-consumer group level.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ReceiverDisconnectedError'
  name: ReceiverDisconnectedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-128">当两个或多个实例连接到同一个分区使用不同的时期值时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-128">Error is thrown when two or more instances connect to the same partition with different epoch values.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ResourceDeletedError'
  name: ResourceDeletedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-129">当客户端使用的服务器实体已被删除时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-129">Error is thrown when a server entity the client is working with has been deleted.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ResourceLockedError'
  name: ResourceLockedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-130">当客户端尝试使用其有访问不能访问因为另一个客户端使用的服务器实体时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-130">Error is thrown when the client attempted to work with a server entity to which it has no access because another client is working with it.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SenderBusyError'
  name: SenderBusyError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-131">当客户端发送方没有足够的链接信用额度，用于发送消息时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-131">Error is thrown when the client sender does not have enough link credits to send the message.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ServerBusyError'
  name: ServerBusyError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-132">服务器正忙时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-132">Error is thrown when the server is busy.</span></span> <span data-ttu-id="67d33-133">调用方应等待一段时间，然后重试该操作。</span><span class="sxs-lookup"><span data-stu-id="67d33-133">Callers should wait a while and retry the operation.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ServiceCommunicationError'
  name: ServiceCommunicationError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-134">用于指示与消息传送操作相关的常规通信错误的错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-134">Error for signaling general communication errors related to messaging operations.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ServiceUnavailableError'
  name: ServiceUnavailableError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-135">该服务不可用时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-135">Error is thrown when the service is unavailable.</span></span> <span data-ttu-id="67d33-136">应重试该操作。</span><span class="sxs-lookup"><span data-stu-id="67d33-136">The operation should be retried.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SessionCannotBeLockedError'
  name: SessionCannotBeLockedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-137">不能锁定 Azure 服务总线会话时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-137">Error is thrown when the Azure ServiceBus session cannot be locked.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SessionLockLostError'
  name: SessionLockLostError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-138">对 Azure 服务总线会话的锁定丢失时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-138">Error is thrown when the lock on the Azure ServiceBus session is lost.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SessionWindowViolationError'
  name: SessionWindowViolationError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-139">对等会话违反传入窗口时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-139">Error is thrown when the peer violated incoming window for the session.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SystemError'
  name: SystemError
  children: []
  langs:
  - typeScript
  summary: >-
    <span data-ttu-id="67d33-140">Node.js 引发低级别系统错误时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-140">Error is thrown when a low level system error is thrown by node.js.</span></span>

    <xref:https%3A%2F%2Fnodejs.org%2Fapi%2Ferrors.html%23errors_class_systemerror>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.TransferLimitExceededError'
  name: TransferLimitExceededError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-141">对等方发送多个消息传送不是当前允许的链接时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-141">Error is thrown when the peer sent more message transfers than currently allowed on the link.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.UnattachedHandleError'
  name: UnattachedHandleError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-142">引用的句柄的当前未使用的附加链接接收的帧 （其他不是附加） 时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-142">Error is thrown when a frame (other than attach) was received referencing a handle which is not currently in use of an attached link.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.NotImplementedError'
  name: NotImplementedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="67d33-143">当一项功能尚未实现，但占位符存在时，将引发错误。</span><span class="sxs-lookup"><span data-stu-id="67d33-143">Error is thrown when a feature is not implemented yet but the placeholder is present.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
